#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSMMaster.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FSM_ITC")]
	public partial class MastersDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MastersDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FSM_ITCConnectionString2"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MastersDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MastersDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MastersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MastersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FTS_CityMaster_List> FTS_CityMaster_Lists
		{
			get
			{
				return this.GetTable<FTS_CityMaster_List>();
			}
		}
		
		public System.Data.Linq.Table<CountryMasterList> CountryMasterLists
		{
			get
			{
				return this.GetTable<CountryMasterList>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FTS_CityMaster_List")]
	public partial class FTS_CityMaster_List
	{
		
		private System.Nullable<int> _USERID;
		
		private System.Nullable<long> _SEQ;
		
		private System.Nullable<int> _city_id;
		
		private System.Nullable<int> _state_id;
		
		private System.Nullable<int> _cou_id;
		
		private string _city_name;
		
		private string _state;
		
		private string _cou_country;
		
		private string _City_NSECode;
		
		private string _City_BSECode;
		
		private string _City_MCXCode;
		
		private string _City_MCXSXCode;
		
		private string _City_NCDEXCode;
		
		private string _City_CDSLCode;
		
		private string _City_NSDLCode;
		
		private string _City_NDMLCode;
		
		private string _City_CVLCode;
		
		private string _City_DotExCode;
		
		private string _City_Lat;
		
		private string _City_Long;
		
		public FTS_CityMaster_List()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="Int")]
		public System.Nullable<int> USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this._USERID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQ", DbType="BigInt")]
		public System.Nullable<long> SEQ
		{
			get
			{
				return this._SEQ;
			}
			set
			{
				if ((this._SEQ != value))
				{
					this._SEQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city_id", DbType="Int")]
		public System.Nullable<int> city_id
		{
			get
			{
				return this._city_id;
			}
			set
			{
				if ((this._city_id != value))
				{
					this._city_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_id", DbType="Int")]
		public System.Nullable<int> state_id
		{
			get
			{
				return this._state_id;
			}
			set
			{
				if ((this._state_id != value))
				{
					this._state_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cou_id", DbType="Int")]
		public System.Nullable<int> cou_id
		{
			get
			{
				return this._cou_id;
			}
			set
			{
				if ((this._cou_id != value))
				{
					this._cou_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city_name", DbType="NVarChar(50)")]
		public string city_name
		{
			get
			{
				return this._city_name;
			}
			set
			{
				if ((this._city_name != value))
				{
					this._city_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="NVarChar(50)")]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cou_country", DbType="NVarChar(50)")]
		public string cou_country
		{
			get
			{
				return this._cou_country;
			}
			set
			{
				if ((this._cou_country != value))
				{
					this._cou_country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City_NSECode", DbType="NVarChar(10)")]
		public string City_NSECode
		{
			get
			{
				return this._City_NSECode;
			}
			set
			{
				if ((this._City_NSECode != value))
				{
					this._City_NSECode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City_BSECode", DbType="NVarChar(10)")]
		public string City_BSECode
		{
			get
			{
				return this._City_BSECode;
			}
			set
			{
				if ((this._City_BSECode != value))
				{
					this._City_BSECode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City_MCXCode", DbType="NVarChar(10)")]
		public string City_MCXCode
		{
			get
			{
				return this._City_MCXCode;
			}
			set
			{
				if ((this._City_MCXCode != value))
				{
					this._City_MCXCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City_MCXSXCode", DbType="NVarChar(10)")]
		public string City_MCXSXCode
		{
			get
			{
				return this._City_MCXSXCode;
			}
			set
			{
				if ((this._City_MCXSXCode != value))
				{
					this._City_MCXSXCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City_NCDEXCode", DbType="NVarChar(10)")]
		public string City_NCDEXCode
		{
			get
			{
				return this._City_NCDEXCode;
			}
			set
			{
				if ((this._City_NCDEXCode != value))
				{
					this._City_NCDEXCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City_CDSLCode", DbType="NVarChar(10)")]
		public string City_CDSLCode
		{
			get
			{
				return this._City_CDSLCode;
			}
			set
			{
				if ((this._City_CDSLCode != value))
				{
					this._City_CDSLCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City_NSDLCode", DbType="NVarChar(10)")]
		public string City_NSDLCode
		{
			get
			{
				return this._City_NSDLCode;
			}
			set
			{
				if ((this._City_NSDLCode != value))
				{
					this._City_NSDLCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City_NDMLCode", DbType="NVarChar(10)")]
		public string City_NDMLCode
		{
			get
			{
				return this._City_NDMLCode;
			}
			set
			{
				if ((this._City_NDMLCode != value))
				{
					this._City_NDMLCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City_CVLCode", DbType="NVarChar(10)")]
		public string City_CVLCode
		{
			get
			{
				return this._City_CVLCode;
			}
			set
			{
				if ((this._City_CVLCode != value))
				{
					this._City_CVLCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City_DotExCode", DbType="NVarChar(10)")]
		public string City_DotExCode
		{
			get
			{
				return this._City_DotExCode;
			}
			set
			{
				if ((this._City_DotExCode != value))
				{
					this._City_DotExCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City_Lat", DbType="NVarChar(MAX)")]
		public string City_Lat
		{
			get
			{
				return this._City_Lat;
			}
			set
			{
				if ((this._City_Lat != value))
				{
					this._City_Lat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City_Long", DbType="NVarChar(MAX)")]
		public string City_Long
		{
			get
			{
				return this._City_Long;
			}
			set
			{
				if ((this._City_Long != value))
				{
					this._City_Long = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CountryMasterList")]
	public partial class CountryMasterList
	{
		
		private System.Nullable<int> _USERID;
		
		private System.Nullable<long> _SEQ;
		
		private System.Nullable<int> _CountryId;
		
		private string _CountryName;
		
		private string _CreateDate;
		
		private string _CreateUser;
		
		private string _ModifyDate;
		
		private string _ModifyUser;
		
		public CountryMasterList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="Int")]
		public System.Nullable<int> USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this._USERID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQ", DbType="BigInt")]
		public System.Nullable<long> SEQ
		{
			get
			{
				return this._SEQ;
			}
			set
			{
				if ((this._SEQ != value))
				{
					this._SEQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryId", DbType="Int")]
		public System.Nullable<int> CountryId
		{
			get
			{
				return this._CountryId;
			}
			set
			{
				if ((this._CountryId != value))
				{
					this._CountryId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryName", DbType="NVarChar(100)")]
		public string CountryName
		{
			get
			{
				return this._CountryName;
			}
			set
			{
				if ((this._CountryName != value))
				{
					this._CountryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="NVarChar(50)")]
		public string CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUser", DbType="NVarChar(100)")]
		public string CreateUser
		{
			get
			{
				return this._CreateUser;
			}
			set
			{
				if ((this._CreateUser != value))
				{
					this._CreateUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="NVarChar(50)")]
		public string ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this._ModifyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyUser", DbType="NVarChar(100)")]
		public string ModifyUser
		{
			get
			{
				return this._ModifyUser;
			}
			set
			{
				if ((this._ModifyUser != value))
				{
					this._ModifyUser = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
